camera_speed_multiplier_rotation: 0.2
debug: false
enable_regenerate: true
example_name: ui_generated
finetune_decoder_gen: true
finetune_decoder_interp: true
finetune_depth_model: true
frames: 10
image_height: 512
image_width: 512
inpainting_resolution_gen: 512
inpainting_resolution_interp: 512
kf2_upsample_coef: 4
num_keyframes: 4
num_scenes: 4
rotation_path:
- 0
- 0
- 0
- 1
- 1
- 0
- 0
- 0
- 0
- 0
- 0
- 1
- 1
- 0
- 0
- 0
rotation_range: 0.45
runs_dir: outputs/wonderjourney
save_fps: 24
seed: -1
skip_gen: false
skip_interp: false
use_gpt: true
